name: Build Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    env:
        PUBLISH_BRANCH: gh-pages # for peaceiris/actions-gh-pages
        PUBLISH_DIR: ./public      # for peaceiris/actions-gh-pages
    steps:
        - name: Checkout
          uses: actions/checkout@v1
          with:
            ref: master
            submodules: recursive

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2.2.2
          with:
            hugo-version: "0.64.0"
            extended: true

        - name: Npm Install
          run: |
            npm install autoprefixer
            npm install postcss-cli
        - name: Build
          run: hugo --gc --minify --cleanDestinationDir

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v2.5.1
          env:
            PERSONAL_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}